baseURL: "https://nyccivilrightshistory.org/"
languageCode: en-us
title: New York City Civil Rights History
description: A Teaching Guide
canonifyURLs: true
relativeURLs: true

params.logo:
    logoText: New York City
    logoHomeLink: /home

menu:
  menu.main:
  - identifier: gallery
    name: Gallery
    url: gallery/

  menu.main:
  - identifier: topics
    name: Topics
    url: topics/

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      footnoteprefix: true
      fn_id_prefix: 'title'
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

defaultContentLanguage: en

mediaTypes:
  application/atom:
    suffixes:
    - xml

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 85
  resampleFilter: box

module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    - source: node_modules/bootstrap/scss
      target: assets/scss/bootstrap
    - source: node_modules/bootstrap/dist/js/bootstrap.min.js
      target: assets/js/bootstrap.min.js

      

# relativeURLs: true

_build:
  list: always
  single: always
  publishResources: true
  render: always

paginate: 20
summaryLength: 7

outputs:
  home:
  - html
  - rss
  - json

taxonomies:
  category: categories
  tag: tags

timeout: 60000
