params:
  baseURL: "https://nyccivilrightshistory.org/"
  languageCode: en-us
  title: New York City Civil Rights History
  description: A teaching and learning guide about the history of NYC Schools
  canonifyURLs: true
  relativeURLs: true
  social:
    twitter: GoHugoIO
  imagesFolder: images

params.logo:
    logoText: New York City
    logoHomeLink: /home
    
menu:
  main:
  - name: About
    pageRef: /about
    weight: 1
  - name: Gallery
    pageRef: /gallery
    weight: 2
  - name: Topics
    pageRef: /topics
    weight: 3
  - name: Key Concepts
    pageRef: /key-concepts
    weight: 4
  - name: Teaching Resources
    pageRef: /teaching-resources
    weight: 5
  - name: Project History
    pageRef: /project-history
    weight: 6
  - name: News and Events
    pageRef: /news-and-events
    weight: 7
  - name: Search
    pageRef: /search
    weight: 8

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      footnoteprefix: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      fn_id_prefix: 'title'
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

defaultContentLanguage: en

mediaTypes:
  application/atom:
    suffixes:
    - xml

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 85
  resampleFilter: box

module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    - source: node_modules/bootstrap/scss
      target: assets/scss/bootstrap
    - source: node_modules/bootstrap/dist/js/bootstrap.min.js
      target: assets/js/bootstrap.min.js

 

# relativeURLs: true

_build:
  list: always
  single: always
  publishResources: true
  render: always

paginate: 20
summaryLength: 7

outputs:
  home:
  - html
  - rss
  - json

taxonomies:
  category: categories
  tag: tags

timeout: 60000


