name: Deploy Hugo site to FTP

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 8 * * *' #every day at 8 am   

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true 
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true

      - name: Build
        run: hugo --minify

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.nyccivilrightshistory.org
          username: nyccivil
          password: ${{ secrets.ftp_password }}
          protocol: sftp
          port: 22
          server-dir: /home/nyccivil/public_html/site-preview/