# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy via FTP

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 8 * * *' #every day at 8 am   
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build site
      run: hugo --minify

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.nyccivilrightshistory.org
        username: nyccivil
        password: ${{ secrets.ftp_password }}
        protocol: sftp
        port: 22
        server-dir: /home/nyccivil/public_html/site-preview/

 
